import { render } from 'inferno'
import './index.css'

const link = 'https://github.com/guocaoyi/create-chrome-ext'

render(
  <main>
    <h3>DevTools Page</h3>
    <a href={link} target="_blank">
      generated by create-chrome-ext
    </a>
  </main>,
  document.getElementById('app'),
)

chrome.devtools.panels.create('InfernoCrx', '', '../../devtools.html', function () {
  console.log('devtools panel create')
})
