/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DevtoolsRoot {
    }
    interface NewtabRoot {
    }
    interface OptionsRoot {
    }
    interface PopupRoot {
    }
    interface SideRoot {
    }
}
declare global {
    interface HTMLDevtoolsRootElement extends Components.DevtoolsRoot, HTMLStencilElement {
    }
    var HTMLDevtoolsRootElement: {
        prototype: HTMLDevtoolsRootElement;
        new (): HTMLDevtoolsRootElement;
    };
    interface HTMLNewtabRootElement extends Components.NewtabRoot, HTMLStencilElement {
    }
    var HTMLNewtabRootElement: {
        prototype: HTMLNewtabRootElement;
        new (): HTMLNewtabRootElement;
    };
    interface HTMLOptionsRootElement extends Components.OptionsRoot, HTMLStencilElement {
    }
    var HTMLOptionsRootElement: {
        prototype: HTMLOptionsRootElement;
        new (): HTMLOptionsRootElement;
    };
    interface HTMLPopupRootElement extends Components.PopupRoot, HTMLStencilElement {
    }
    var HTMLPopupRootElement: {
        prototype: HTMLPopupRootElement;
        new (): HTMLPopupRootElement;
    };
    interface HTMLSideRootElement extends Components.SideRoot, HTMLStencilElement {
    }
    var HTMLSideRootElement: {
        prototype: HTMLSideRootElement;
        new (): HTMLSideRootElement;
    };
    interface HTMLElementTagNameMap {
        "devtools-root": HTMLDevtoolsRootElement;
        "newtab-root": HTMLNewtabRootElement;
        "options-root": HTMLOptionsRootElement;
        "popup-root": HTMLPopupRootElement;
        "side-root": HTMLSideRootElement;
    }
}
declare namespace LocalJSX {
    interface DevtoolsRoot {
    }
    interface NewtabRoot {
    }
    interface OptionsRoot {
    }
    interface PopupRoot {
    }
    interface SideRoot {
    }
    interface IntrinsicElements {
        "devtools-root": DevtoolsRoot;
        "newtab-root": NewtabRoot;
        "options-root": OptionsRoot;
        "popup-root": PopupRoot;
        "side-root": SideRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "devtools-root": LocalJSX.DevtoolsRoot & JSXBase.HTMLAttributes<HTMLDevtoolsRootElement>;
            "newtab-root": LocalJSX.NewtabRoot & JSXBase.HTMLAttributes<HTMLNewtabRootElement>;
            "options-root": LocalJSX.OptionsRoot & JSXBase.HTMLAttributes<HTMLOptionsRootElement>;
            "popup-root": LocalJSX.PopupRoot & JSXBase.HTMLAttributes<HTMLPopupRootElement>;
            "side-root": LocalJSX.SideRoot & JSXBase.HTMLAttributes<HTMLSideRootElement>;
        }
    }
}
